### PR TITLE
Added the Addition Feature

### PR DESCRIPTION
**Pull request by princyballabh**
---
name: Pull Request
about: Create a pull request to contribute to this repository
title: ''
labels: ''
assignees: ''
---

**Is your pull request related to an issue?**

If so, please link the issue here: [Link to the issue]

**Describe your Pull Request**

A clear and concise description of what you have done and why.

**Changes Made**

Added addition feature for the calculator in c language

**Screenshots**

If applicable, add screenshots to showcase the changes.

**Checklist**

- [ ] I have tested my changes thoroughly.
- [ ] My code follows the project's coding guidelines.
- [ ] I have added necessary documentation (if applicable).
- [ ] I have updated the README (if applicable).
- [ ] All new and existing tests passed.
- [ ] I have signed the Contributor License Agreement.

**Additional Comments**

Any additional information or context.

**Related Issues**

- Fixes #[Issue Number]
- Closes #[Issue Number]

### CODE REVIEW

**Review by rahuldahal — COMMENTED** [review]
Do you know how to take input from the main function: `argv`(Argument Vector)?
If you do, update your code to take input from the CLI. Else, current implementation is fine as well.
[Further details about the topic](https://www.geeksforgeeks.org/command-line-arguments-in-c-cpp/)

**Comment by princyballabh** [comment]
I have updated the file. Actually I have never used CLI before, just watched some tutorials and tried to make changes. If the code is incorrect then do let me know. I will implement the earlier code.

**Review by rahuldahal — CHANGES_REQUESTED** [review]
The functionality works fine(gives the expected output when provided expected input).
It throws a warning about `atoi`, which can be fixed by including the `#include <stdlib.h>` header file.

I want to make sure everything is perfect and at the same time guide you guys to improve the code.

**Comment by princyballabh** [comment]
Thank you so much for guiding! I have added the required header file

**Review by rahuldahal — APPROVED** [review]
🥂 👍

**Pull request merged**
